# Generated by Django 4.2.7 on 2024-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
