# Generated by Django 4.2.7 on 2024-02-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0006_alter_order_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="slip",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "ยังไม่ชำระเงิน"),
                    ("2", "รอตรวจสอบสลิป"),
                    ("3", "ชำระเงินเสร็จสิ้น"),
                    ("4", "ส่งสลิปใหม่"),
                ],
                default=1,
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("slip", models.ImageField(blank=True, upload_to="slip")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_order.order",
                    ),
                ),
            ],
        ),
    ]
