# Generated by Django 4.2.7 on 2024-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0007_remove_order_slip_order_status_order_update_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="slip",
            field=models.ImageField(blank=True, upload_to="slip"),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
