# Generated by Django 4.2.7 on 2024-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0008_order_slip_delete_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "รอตรวจสอบสลิป"),
                    ("2", "ชำระเงินเสร็จสิ้น"),
                    ("3", "ส่งสลิปใหม่"),
                ],
                default=1,
                max_length=255,
            ),
        ),
    ]
