# Generated by Django 4.2.7 on 2024-01-24 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_alter_cart_customer_alter_customer_phone"),
        ("user_app", "0002_alter_cart_customer_customerprofile_delete_customer"),
    ]

    operations = []
