# Generated by Django 4.2.7 on 2024-01-31 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_app", "0003_merge_20240124_1529"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerProfile",
            new_name="Customer",
        ),
    ]
