# Generated by Django 4.2.7 on 2024-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_rename_customerprofile_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
