# Generated by Django 4.2.7 on 2024-03-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_remove_orderdetail_order_delete_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
