# Generated by Django 4.2.7 on 2024-02-20 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bakery_app", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
