# Generated by Django 4.2.7 on 2024-02-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bakery_app", "0003_remove_product_amount_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="ขนมปัง", max_length=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="descriptions",
            field=models.CharField(default="ขนมปัง", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="ขนมปัง", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default="20"),
            preserve_default=False,
        ),
    ]
