# Generated by Django 4.2.7 on 2024-02-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bakery_app",
            "0004_product_amount_product_category_product_descriptions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="descriptions",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
